### ISSUE TITLE
Class craft\commerce\taxjar\engines\TaxJar should implement "isSelectable"

### ISSUE THREAD

**Issue by klemenb** [craftcms/commerce-taxjar#4]
### Description

Error thrown with Craft 3.5:

`Class craft\commerce\taxjar\engines\TaxJar contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\base\ComponentInterface::isSelectable)`

ComponentInterface::isSelectable was apparently added in Craft 3.5:

```
/**
 * Returns whether the component should be selectable in component Type selects.
 *
 * @return bool whether the component should be selectable in component Type selects.
 * @since 3.5.0
 */
public static function isSelectable(): bool;
```

### Steps to reproduce

1. Install the plugin
2. Go to "Commerce" -> "Tax" in the admin panel

### Additional info

- Craft version: 3.5
- PHP version: 7.4
- Plugins & versions: Craft Commerce 3.2

**Comment by christopherhealey** [comment]
if this pull request solves the problem could we get it merged? Been over a month now.
