### ISSUE TITLE
Updating to 3.5 causes error

### ISSUE THREAD

**Issue by geenious** [craftcms/commerce-taxjar#7]
### Description
When I update my commerce site from Craft v3.4.28.1 to v3.5.14, the TaxJar plugin produces this error:
`PHP Fatal Error – yii\base\ErrorException
Class craft\commerce\taxjar\engines\TaxJar contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\base\ComponentInterface::isSelectable)
1. in /Volumes/dev/goodwork/goldpawseries/vendor/craftcms/commerce-taxjar/src/engines/TaxJar.php at line 21`

I've tried updating to Commerce v3.2.10, but the error remains.

### Additional info

- Craft version: 3.4.28.1 -> 3.5.14
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions:
  -  Craft Commerce (Pro) 3.1.12
  -  TaxJar 1.0.0

**Comment by aladrach** [comment]
Any updates on a possible fix for this?

**Comment by mattcdavis1** [comment]
just need to add the missing method to `craft\commerce\taxjar\engines\Craft`:

```
public static function isSelectable(): bool
{
    return false;
}
```
